package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestGenerateMarkdownReport tests report generation
func TestGenerateMarkdownReport(t *testing.T) {
	tempDir := t.TempDir()

	result := &ScanResult{
		TotalFiles:        100,
		CorruptedFiles:    []CorruptedFile{},
		EPUBTotal:         50,
		EPUBCorrupted:     2,
		MOBITotal:         30,
		MOBICorrupted:     1,
		PDFTotal:          20,
		PDFCorrupted:      0,
		EmptyFolders:      []string{},
		TotalFolders:      10,
		FoldersWithEbooks: 8,
	}

	reportPath, err := GenerateMarkdownReport(result, tempDir, "CORRUPTED")

	if err != nil {
		t.Fatalf("GenerateMarkdownReport failed: %v", err)
	}

	// Check that report file was created
	if _, err := os.Stat(reportPath); os.IsNotExist(err) {
		t.Errorf("Expected report file to be created at %s", reportPath)
	}

	// Read report content
	content, err := os.ReadFile(reportPath)
	if err != nil {
		t.Fatalf("Failed to read report: %v", err)
	}

	contentStr := string(content)

	// Verify report contains key sections
	if !strings.Contains(contentStr, "# EbookMechanic Report") {
		t.Error("Expected report to contain title")
	}

	if !strings.Contains(contentStr, "Corruption Scan Summary") {
		t.Error("Expected report to contain corruption summary")
	}

	if !strings.Contains(contentStr, "Empty Folders Summary") {
		t.Error("Expected report to contain empty folders summary")
	}

	if !strings.Contains(contentStr, "**Total files scanned:** 100") {
		t.Error("Expected report to contain total files count")
	}

	if !strings.Contains(contentStr, "*Report generated by EbookMechanic*") {
		t.Error("Expected report to contain footer")
	}
}

// TestGenerateMarkdownReportWithCorruptedFiles tests report with corrupted files
func TestGenerateMarkdownReportWithCorruptedFiles(t *testing.T) {
	tempDir := t.TempDir()

	corruptedFile := filepath.Join(tempDir, "books", "corrupted.epub")

	result := &ScanResult{
		TotalFiles: 10,
		CorruptedFiles: []CorruptedFile{
			{
				Path:   corruptedFile,
				Reason: "Missing mimetype file",
				Size:   1024,
			},
		},
		EPUBTotal:     5,
		EPUBCorrupted: 1,
		MOBITotal:     3,
		MOBICorrupted: 0,
		PDFTotal:      2,
		PDFCorrupted:  0,
		EmptyFolders:  []string{},
		TotalFolders:  5,
	}

	reportPath, err := GenerateMarkdownReport(result, tempDir, "CORRUPTED")
	if err != nil {
		t.Fatalf("GenerateMarkdownReport failed: %v", err)
	}

	content, err := os.ReadFile(reportPath)
	if err != nil {
		t.Fatalf("Failed to read report: %v", err)
	}

	contentStr := string(content)

	// Check that corrupted files section exists
	if !strings.Contains(contentStr, "Corrupted Files Details") {
		t.Error("Expected report to contain corrupted files details")
	}

	if !strings.Contains(contentStr, "### EPUB Files") {
		t.Error("Expected report to contain EPUB files section")
	}

	if !strings.Contains(contentStr, "Missing mimetype file") {
		t.Error("Expected report to contain corruption reason")
	}

	if !strings.Contains(contentStr, "1.0 KB") {
		t.Error("Expected report to contain formatted file size")
	}
}

// TestGenerateMarkdownReportWithEmptyFolders tests report with empty folders
func TestGenerateMarkdownReportWithEmptyFolders(t *testing.T) {
	tempDir := t.TempDir()

	// Create test directories
	emptyDir1 := filepath.Join(tempDir, "empty1")
	emptyDir2 := filepath.Join(tempDir, "empty2")
	os.Mkdir(emptyDir1, 0755)
	os.Mkdir(emptyDir2, 0755)

	// Add some files to emptyDir1 for content display
	os.WriteFile(filepath.Join(emptyDir1, "file1.txt"), []byte("test"), 0644)
	os.WriteFile(filepath.Join(emptyDir1, "file2.txt"), []byte("test"), 0644)

	result := &ScanResult{
		TotalFiles:     0,
		CorruptedFiles: []CorruptedFile{},
		EmptyFolders:   []string{emptyDir1, emptyDir2},
		TotalFolders:   2,
	}

	reportPath, err := GenerateMarkdownReport(result, tempDir, "CORRUPTED")
	if err != nil {
		t.Fatalf("GenerateMarkdownReport failed: %v", err)
	}

	content, err := os.ReadFile(reportPath)
	if err != nil {
		t.Fatalf("Failed to read report: %v", err)
	}

	contentStr := string(content)

	// Check that empty folders section exists
	if !strings.Contains(contentStr, "Folders Without Ebooks") {
		t.Error("Expected report to contain folders without ebooks section")
	}

	if !strings.Contains(contentStr, "empty1") {
		t.Error("Expected report to contain empty folder name")
	}

	if !strings.Contains(contentStr, "**Contents:** 2 items") {
		t.Error("Expected report to contain folder contents count")
	}
}

// TestGenerateMarkdownReportNoIssues tests report when no issues found
func TestGenerateMarkdownReportNoIssues(t *testing.T) {
	tempDir := t.TempDir()

	result := &ScanResult{
		TotalFiles:        50,
		CorruptedFiles:    []CorruptedFile{},
		EPUBTotal:         30,
		EPUBCorrupted:     0,
		MOBITotal:         15,
		MOBICorrupted:     0,
		PDFTotal:          5,
		PDFCorrupted:      0,
		EmptyFolders:      []string{},
		TotalFolders:      5,
		FoldersWithEbooks: 5,
	}

	reportPath, err := GenerateMarkdownReport(result, tempDir, "CORRUPTED")
	if err != nil {
		t.Fatalf("GenerateMarkdownReport failed: %v", err)
	}

	content, err := os.ReadFile(reportPath)
	if err != nil {
		t.Fatalf("Failed to read report: %v", err)
	}

	contentStr := string(content)

	// Check that success messages are shown
	if !strings.Contains(contentStr, "No Corrupted Files Found") {
		t.Error("Expected report to contain 'No Corrupted Files Found'")
	}

	if !strings.Contains(contentStr, "No Empty Folders Found") {
		t.Error("Expected report to contain 'No Empty Folders Found'")
	}

	// Check for checkmarks in table
	if !strings.Contains(contentStr, "✅") {
		t.Error("Expected report to contain checkmarks for clean files")
	}
}

// TestStatusMark tests the statusMark helper function
func TestStatusMark(t *testing.T) {
	if statusMark(0) != "✅" {
		t.Errorf("Expected '✅' for 0 corrupted, got '%s'", statusMark(0))
	}

	if statusMark(1) != "❌" {
		t.Errorf("Expected '❌' for 1 corrupted, got '%s'", statusMark(1))
	}

	if statusMark(5) != "❌" {
		t.Errorf("Expected '❌' for 5 corrupted, got '%s'", statusMark(5))
	}
}

// TestFilterByExt tests the filterByExt helper function
func TestFilterByExt(t *testing.T) {
	files := []CorruptedFile{
		{Path: "/path/to/book1.epub", Reason: "test", Size: 100},
		{Path: "/path/to/book2.mobi", Reason: "test", Size: 200},
		{Path: "/path/to/book3.epub", Reason: "test", Size: 300},
		{Path: "/path/to/book4.pdf", Reason: "test", Size: 400},
	}

	epubFiles := filterByExt(files, ".epub")
	if len(epubFiles) != 2 {
		t.Errorf("Expected 2 EPUB files, got %d", len(epubFiles))
	}

	mobiFiles := filterByExt(files, ".mobi")
	if len(mobiFiles) != 1 {
		t.Errorf("Expected 1 MOBI file, got %d", len(mobiFiles))
	}

	pdfFiles := filterByExt(files, ".pdf")
	if len(pdfFiles) != 1 {
		t.Errorf("Expected 1 PDF file, got %d", len(pdfFiles))
	}

	azw3Files := filterByExt(files, ".azw3")
	if len(azw3Files) != 0 {
		t.Errorf("Expected 0 AZW3 files, got %d", len(azw3Files))
	}
}

// TestFormatBytes tests the formatBytes helper function
func TestFormatBytes(t *testing.T) {
	tests := []struct {
		bytes    int64
		expected string
	}{
		{0, "0 B"},
		{100, "100 B"},
		{1023, "1023 B"},
		{1024, "1.0 KB"},
		{1536, "1.5 KB"},
		{1048576, "1.0 MB"},
		{1572864, "1.5 MB"},
		{1073741824, "1.0 GB"},
		{1099511627776, "1.0 TB"},
	}

	for _, test := range tests {
		result := formatBytes(test.bytes)
		if result != test.expected {
			t.Errorf("formatBytes(%d) = %s, expected %s", test.bytes, result, test.expected)
		}
	}
}

// TestReportFilename tests that report filename includes timestamp
func TestReportFilename(t *testing.T) {
	tempDir := t.TempDir()

	result := &ScanResult{
		TotalFiles:     0,
		CorruptedFiles: []CorruptedFile{},
		EmptyFolders:   []string{},
	}

	reportPath, err := GenerateMarkdownReport(result, tempDir, "CORRUPTED")
	if err != nil {
		t.Fatalf("GenerateMarkdownReport failed: %v", err)
	}

	filename := filepath.Base(reportPath)

	if !strings.HasPrefix(filename, "ebook_mechanic_report_") {
		t.Errorf("Expected filename to start with 'ebook_mechanic_report_', got '%s'", filename)
	}

	if !strings.HasSuffix(filename, ".md") {
		t.Errorf("Expected filename to end with '.md', got '%s'", filename)
	}
}

// TestReportTableFormat tests that the report includes proper markdown table
func TestReportTableFormat(t *testing.T) {
	tempDir := t.TempDir()

	result := &ScanResult{
		TotalFiles:    10,
		EPUBTotal:     5,
		EPUBCorrupted: 1,
		MOBITotal:     3,
		MOBICorrupted: 0,
		PDFTotal:      2,
		PDFCorrupted:  0,
	}

	reportPath, err := GenerateMarkdownReport(result, tempDir, "CORRUPTED")
	if err != nil {
		t.Fatalf("GenerateMarkdownReport failed: %v", err)
	}

	content, err := os.ReadFile(reportPath)
	if err != nil {
		t.Fatalf("Failed to read report: %v", err)
	}

	contentStr := string(content)

	// Check table structure
	if !strings.Contains(contentStr, "| File Type | Corrupted | Total | Status |") {
		t.Error("Expected report to contain table header")
	}

	if !strings.Contains(contentStr, "|-----------|-----------|-------|--------|") {
		t.Error("Expected report to contain table separator")
	}

	if !strings.Contains(contentStr, "| EPUB | 1 | 5 |") {
		t.Error("Expected report to contain EPUB row")
	}

	if !strings.Contains(contentStr, "| MOBI | 0 | 3 |") {
		t.Error("Expected report to contain MOBI row")
	}

	if !strings.Contains(contentStr, "| PDF | 0 | 2 |") {
		t.Error("Expected report to contain PDF row")
	}
}
